# automatically generated by the FlatBuffers compiler, do not modify

# namespace: PPLProtocol

import flatbuffers

class HandshakeResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsHandshakeResult(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HandshakeResult()
        x.Init(buf, n + offset)
        return x

    # HandshakeResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HandshakeResult
    def SystemName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # HandshakeResult
    def ModelName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

def HandshakeResultStart(builder): builder.StartObject(2)
def HandshakeResultAddSystemName(builder, systemName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(systemName), 0)
def HandshakeResultAddModelName(builder, modelName): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(modelName), 0)
def HandshakeResultEnd(builder): return builder.EndObject()
