# automatically generated by the FlatBuffers compiler, do not modify

# namespace: PPLProtocol

class MessageBody(object):
    NONE = 0
    Run = 1
    RunResult = 2
    Sample = 3
    SampleResult = 4
    Observe = 5
    ObserveResult = 6

