# automatically generated by the FlatBuffers compiler, do not modify

# namespace: PPLProtocol

import flatbuffers

class ObserveResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsObserveResult(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ObserveResult()
        x.Init(buf, n + offset)
        return x

    # ObserveResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ObserveResultStart(builder): builder.StartObject(0)
def ObserveResultEnd(builder): return builder.EndObject()
