# automatically generated by the FlatBuffers compiler, do not modify

# namespace: PPLProtocol

import flatbuffers

class Run(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRun(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Run()
        x.Init(buf, n + offset)
        return x

    # Run
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Run
    def Observation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .ProtocolTensor import ProtocolTensor
            obj = ProtocolTensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RunStart(builder): builder.StartObject(1)
def RunAddObservation(builder, observation): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(observation), 0)
def RunEnd(builder): return builder.EndObject()
