# automatically generated by the FlatBuffers compiler, do not modify

# namespace: PPLProtocol

import flatbuffers

class SampleResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSampleResult(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SampleResult()
        x.Init(buf, n + offset)
        return x

    # SampleResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SampleResult
    def Result(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .ProtocolTensor import ProtocolTensor
            obj = ProtocolTensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SampleResultStart(builder): builder.StartObject(1)
def SampleResultAddResult(builder, result): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)
def SampleResultEnd(builder): return builder.EndObject()
