# automatically generated by the FlatBuffers compiler, do not modify

# namespace: PPLProtocol

import flatbuffers

class Uniform(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUniform(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Uniform()
        x.Init(buf, n + offset)
        return x

    # Uniform
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Uniform
    def Low(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Uniform
    def High(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def UniformStart(builder): builder.StartObject(2)
def UniformAddLow(builder, low): builder.PrependFloat64Slot(0, low, 0.0)
def UniformAddHigh(builder, high): builder.PrependFloat64Slot(1, high, 0.0)
def UniformEnd(builder): return builder.EndObject()
