# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class Categorical(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCategorical(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Categorical()
        x.Init(buf, n + offset)
        return x

    # Categorical
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Categorical
    def PriorSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Categorical
    def ProposalProbabilities(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .NDArray import NDArray
            obj = NDArray()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CategoricalStart(builder): builder.StartObject(2)
def CategoricalAddPriorSize(builder, priorSize): builder.PrependInt32Slot(0, priorSize, 0)
def CategoricalAddProposalProbabilities(builder, proposalProbabilities): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(proposalProbabilities), 0)
def CategoricalEnd(builder): return builder.EndObject()
