# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class DiscreteProposal(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDiscreteProposal(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DiscreteProposal()
        x.Init(buf, n + offset)
        return x

    # DiscreteProposal
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DiscreteProposal
    def Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DiscreteProposal
    def Probabilities(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .NDArray import NDArray
            obj = NDArray()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def DiscreteProposalStart(builder): builder.StartObject(2)
def DiscreteProposalAddSize(builder, size): builder.PrependInt32Slot(0, size, 0)
def DiscreteProposalAddProbabilities(builder, probabilities): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(probabilities), 0)
def DiscreteProposalEnd(builder): return builder.EndObject()
