# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

class Distribution(object):
    NONE = 0
    Categorical = 1
    Discrete = 2
    Flip = 3
    Normal = 4
    UniformDiscrete = 5
    VMF = 6
    Poisson = 7
    UniformContinuous = 8
    MultivariateNormal = 9

