# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class FlipProposal(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFlipProposal(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlipProposal()
        x.Init(buf, n + offset)
        return x

    # FlipProposal
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FlipProposal
    def Probability(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def FlipProposalStart(builder): builder.StartObject(1)
def FlipProposalAddProbability(builder, probability): builder.PrependFloat64Slot(0, probability, 0.0)
def FlipProposalEnd(builder): return builder.EndObject()
