# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class NormalProposal(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNormalProposal(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NormalProposal()
        x.Init(buf, n + offset)
        return x

    # NormalProposal
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NormalProposal
    def Mean(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # NormalProposal
    def Std(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def NormalProposalStart(builder): builder.StartObject(2)
def NormalProposalAddMean(builder, mean): builder.PrependFloat64Slot(0, mean, 0.0)
def NormalProposalAddStd(builder, std): builder.PrependFloat64Slot(1, std, 0.0)
def NormalProposalEnd(builder): return builder.EndObject()
