# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class ObservesInitReply(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsObservesInitReply(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ObservesInitReply()
        x.Init(buf, n + offset)
        return x

    # ObservesInitReply
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ObservesInitReply
    def Success(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
        return 0

def ObservesInitReplyStart(builder): builder.StartObject(1)
def ObservesInitReplyAddSuccess(builder, success): builder.PrependBoolSlot(0, success, 0)
def ObservesInitReplyEnd(builder): return builder.EndObject()
