# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class ProposalReply(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsProposalReply(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProposalReply()
        x.Init(buf, n + offset)
        return x

    # ProposalReply
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProposalReply
    def ProposalType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ProposalReply
    def Proposal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ProposalReplyStart(builder): builder.StartObject(2)
def ProposalReplyAddProposalType(builder, proposalType): builder.PrependUint8Slot(0, proposalType, 0)
def ProposalReplyAddProposal(builder, proposal): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(proposal), 0)
def ProposalReplyEnd(builder): return builder.EndObject()
