# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

class ProposalDistribution(object):
    NONE = 0
    CategoricalProposal = 1
    DiscreteProposal = 2
    FlipProposal = 3
    NormalProposal = 4
    UniformDiscreteProposal = 5
