# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

class ProposalDistribution(object):
    NONE = 0
    UniformDiscreteProposal = 1
    NormalProposal = 2

