# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

class Reply(object):
    NONE = 0
    TracesFromPriorReply = 1
    ObservesInitReply = 2
    ProposalReply = 3

