# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

class Request(object):
    NONE = 0
    TracesFromPriorRequest = 1
    ObservesInitRequest = 2
    ProposalRequest = 3

