# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

class Distribution(object):
    NONE = 0
    Beta = 1
    Categorical = 2
    Discrete = 3
    Flip = 4
    Gamma = 5
    Laplace = 6
    MultivariateNormal = 7
    Normal = 8
    Poisson = 9
    UniformContinuous = 10
    UniformDiscrete = 11
    VMF = 12

