# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

class Distribution(object):
    NONE = 0
    Beta = 1
    Discrete = 2
    Flip = 3
    Gamma = 4
    Laplace = 5
    Mixture = 6
    MultivariateNormal = 7
    Normal = 8
    Poisson = 9
    Truncated = 10
    UniformContinuous = 11
    UniformDiscrete = 12

