# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers

class Flip(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFlip(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Flip()
        x.Init(buf, n + offset)
        return x

    # Flip
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Flip
    def Probability(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def FlipStart(builder): builder.StartObject(1)
def FlipAddProbability(builder, probability): builder.PrependFloat64Slot(0, probability, 0.0)
def FlipEnd(builder): return builder.EndObject()
