# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers

class Gamma(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGamma(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Gamma()
        x.Init(buf, n + offset)
        return x

    # Gamma
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Gamma
    def ProposalLocation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Gamma
    def ProposalScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def GammaStart(builder): builder.StartObject(2)
def GammaAddProposalLocation(builder, proposalLocation): builder.PrependFloat64Slot(0, proposalLocation, 0.0)
def GammaAddProposalScale(builder, proposalScale): builder.PrependFloat64Slot(1, proposalScale, 0.0)
def GammaEnd(builder): return builder.EndObject()
