# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

class MessageBody(object):
    NONE = 0
    RequestTraces = 1
    ReplyTraces = 2
    RequestFinishCompilation = 3
    ReplyFinishCompilation = 4
    RequestStartInference = 5
    ReplyStartInference = 6
    RequestFinishInference = 7
    ReplyFinishInference = 8
    RequestProposal = 9
    ReplyProposal = 10

