# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

class MessageBody(object):
    NONE = 0
    TracesFromPriorRequest = 1
    ObservesInitRequest = 2
    ProposalRequest = 3
    TracesFromPriorReply = 4
    ObservesInitReply = 5
    ProposalReply = 6

