# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers

class Mixture(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMixture(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Mixture()
        x.Init(buf, n + offset)
        return x

    # Mixture
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Mixture
    def Coefficients(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Mixture
    def CoefficientsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # Mixture
    def CoefficientsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Mixture
    def Distributions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .NestedDistribution import NestedDistribution
            obj = NestedDistribution()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Mixture
    def DistributionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def MixtureStart(builder): builder.StartObject(2)
def MixtureAddCoefficients(builder, coefficients): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(coefficients), 0)
def MixtureStartCoefficientsVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def MixtureAddDistributions(builder, distributions): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(distributions), 0)
def MixtureStartDistributionsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def MixtureEnd(builder): return builder.EndObject()
