# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers

class ReplyFinishCompilation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsReplyFinishCompilation(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReplyFinishCompilation()
        x.Init(buf, n + offset)
        return x

    # ReplyFinishCompilation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ReplyFinishCompilationStart(builder): builder.StartObject(0)
def ReplyFinishCompilationEnd(builder): return builder.EndObject()
