# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers

class ReplyFinishInference(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsReplyFinishInference(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReplyFinishInference()
        x.Init(buf, n + offset)
        return x

    # ReplyFinishInference
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ReplyFinishInferenceStart(builder): builder.StartObject(0)
def ReplyFinishInferenceEnd(builder): return builder.EndObject()
