# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers

class ReplyTraces(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsReplyTraces(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReplyTraces()
        x.Init(buf, n + offset)
        return x

    # ReplyTraces
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReplyTraces
    def Traces(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Trace import Trace
            obj = Trace()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ReplyTraces
    def TracesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def ReplyTracesStart(builder): builder.StartObject(1)
def ReplyTracesAddTraces(builder, traces): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(traces), 0)
def ReplyTracesStartTracesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ReplyTracesEnd(builder): return builder.EndObject()
