# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers

class RequestFinishCompilation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRequestFinishCompilation(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestFinishCompilation()
        x.Init(buf, n + offset)
        return x

    # RequestFinishCompilation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def RequestFinishCompilationStart(builder): builder.StartObject(0)
def RequestFinishCompilationEnd(builder): return builder.EndObject()
