# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers

class RequestFinishInference(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRequestFinishInference(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestFinishInference()
        x.Init(buf, n + offset)
        return x

    # RequestFinishInference
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def RequestFinishInferenceStart(builder): builder.StartObject(0)
def RequestFinishInferenceEnd(builder): return builder.EndObject()
