# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers

class RequestStartInference(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRequestStartInference(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestStartInference()
        x.Init(buf, n + offset)
        return x

    # RequestStartInference
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RequestStartInference
    def Observation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RequestStartInferenceStart(builder): builder.StartObject(1)
def RequestStartInferenceAddObservation(builder, observation): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(observation), 0)
def RequestStartInferenceEnd(builder): return builder.EndObject()
