# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers

class RequestTraces(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRequestTraces(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestTraces()
        x.Init(buf, n + offset)
        return x

    # RequestTraces
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RequestTraces
    def NumTraces(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def RequestTracesStart(builder): builder.StartObject(1)
def RequestTracesAddNumTraces(builder, numTraces): builder.PrependInt32Slot(0, numTraces, 0)
def RequestTracesEnd(builder): return builder.EndObject()
