# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers

class UniformDiscrete(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUniformDiscrete(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UniformDiscrete()
        x.Init(buf, n + offset)
        return x

    # UniformDiscrete
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UniformDiscrete
    def PriorMin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UniformDiscrete
    def PriorSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UniformDiscrete
    def ProposalProbabilities(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .NDArray import NDArray
            obj = NDArray()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def UniformDiscreteStart(builder): builder.StartObject(3)
def UniformDiscreteAddPriorMin(builder, priorMin): builder.PrependInt32Slot(0, priorMin, 0)
def UniformDiscreteAddPriorSize(builder, priorSize): builder.PrependInt32Slot(1, priorSize, 0)
def UniformDiscreteAddProposalProbabilities(builder, proposalProbabilities): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(proposalProbabilities), 0)
def UniformDiscreteEnd(builder): return builder.EndObject()
