# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers

class UniformContinuous(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUniformContinuous(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UniformContinuous()
        x.Init(buf, n + offset)
        return x

    # UniformContinuous
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UniformContinuous
    def PriorMin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # UniformContinuous
    def PriorMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # UniformContinuous
    def ProposalMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # UniformContinuous
    def ProposalCertainty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def UniformContinuousStart(builder): builder.StartObject(4)
def UniformContinuousAddPriorMin(builder, priorMin): builder.PrependFloat64Slot(0, priorMin, 0.0)
def UniformContinuousAddPriorMax(builder, priorMax): builder.PrependFloat64Slot(1, priorMax, 0.0)
def UniformContinuousAddProposalMode(builder, proposalMode): builder.PrependFloat64Slot(2, proposalMode, 0.0)
def UniformContinuousAddProposalCertainty(builder, proposalCertainty): builder.PrependFloat64Slot(3, proposalCertainty, 0.0)
def UniformContinuousEnd(builder): return builder.EndObject()
