# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ppx

class Distribution(object):
    NONE = 0
    Normal = 1
    Uniform = 2
    Categorical = 3
    Poisson = 4
    Gamma = 5
    LogNormal = 6
    Exponential = 7
    Weibull = 8

