# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ppx

class Distribution(object):
    NONE = 0
    Normal = 1
    Uniform = 2
    Categorical = 3
    Poisson = 4
    Bernoulli = 5
    Beta = 6
    Exponential = 7
    Gamma = 8
    LogNormal = 9
    Binomial = 10
    Weibull = 11

