# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ppx

class MessageBody(object):
    NONE = 0
    Handshake = 1
    HandshakeResult = 2
    Run = 3
    RunResult = 4
    Sample = 5
    SampleResult = 6
    Observe = 7
    ObserveResult = 8
    Tag = 9
    TagResult = 10
    Reset = 11

