# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ppx

import flatbuffers

class Run(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRun(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Run()
        x.Init(buf, n + offset)
        return x

    # Run
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def RunStart(builder): builder.StartObject(0)
def RunEnd(builder): return builder.EndObject()
