# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ppx

import flatbuffers

class TagResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTagResult(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TagResult()
        x.Init(buf, n + offset)
        return x

    # TagResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def TagResultStart(builder): builder.StartObject(0)
def TagResultEnd(builder): return builder.EndObject()
