# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ppx

import flatbuffers

class Weibull(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsWeibull(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Weibull()
        x.Init(buf, n + offset)
        return x

    # Weibull
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Weibull
    def Scale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Weibull
    def Concetration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WeibullStart(builder): builder.StartObject(2)
def WeibullAddScale(builder, scale): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(scale), 0)
def WeibullAddConcetration(builder, concetration): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(concetration), 0)
def WeibullEnd(builder): return builder.EndObject()
